-- Buat di Supabase SQL Editor
create table produk (
  id bigint generated by default as identity primary key,
  nama text not null,
  harga integer not null,
  kategori text,
  stok integer default 50,
  gambar text,
  deskripsi text,
  terlaris boolean default false,
  created_at timestamp default now()
);

create table pesanan (
  id text primary key, -- TRX timestamp
  user_email text,
  user_nama text,
  items jsonb,
  total integer,
  ongkir integer,
  layanan text,
  metode text, -- COD / E-Wallet
  status text, -- Menunggu Pembayaran / Diproses / Dikirim / Selesai / Gagal
  alamat text,
  doku_invoice text,
  doku_payment_url text,
  created_at timestamp default now()
);

-- Enable realtime
alter publication supabase_realtime add table produk;
alter publication supabase_realtime add table pesanan;

-- Policy biar bisa diakses tanpa login (untuk toko kecil, nanti bisa pakai RLS)
alter table produk enable row level security;
alter table pesanan enable row level security;
create policy "public all produk" on produk for all using (true) with check (true);
create policy "public all pesanan" on pesanan for all using (true) with check (true);
